// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {boolean} isEnabled
 * @returns {Promise.<void>}
 */
export async function JS_DarkMode(isEnabled) {
	// BEGIN USER CODE
	if(isEnabled){
		document.body.classList.add("darkmode");
	}else{
		document.body.classList.remove("darkmode");
	}
	// END USER CODE
}
